services:
  ydev_web:
    build: ydev_web
    ports: 
      - 5173:5173
    expose:
      - 5173
  ydev_app: 
    build:
      context: ydev_app 
      target: dev-envs
    ports: 
      - 8080:8080
    expose: 
      - 8080
  ydev_db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ydev
      MYSQL_ROOT_PASSWORD: password
    expose: 
      - 3306
