services:
  ydev_app: 
    build:
      context: ydev_app 
      target: dev-envs
    environment:
      JAR_FILE: ydev-0.0.1-jar-with-dependencies.jar
    ports: 
      - 8080:8080
    expose:
      - 8080
    depends_on:
      ydev_db:
        condition: service_healthy 

  ydev_db:
    build: ydev_db
    image: mariadb:11.5.1-ubi9-rc 
    restart: always
    environment:
      MYSQL_DATABASE: ydev-db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=password"]
      interval: 30s
      timeout: 10s
      retries: 3
