services:
  ydev_web:
    build: ydev_web
    ports: 
      - 3000:3000
  ydev_app: 
    build: ydev_app 
    ports: 
      - 8080:8080
    secrets:
      - db-password
  ydev_db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ydev
      MYSQL_ROOT_PASSWORD: password
    expose: 
      - 3306
    volumes:
      - db-data:/var/lib/mysql
  volumes:
    db-data:
  secrets:
    db-password:
      file: db/password.txt


